
ifndef EXPORT_ONLY
	configure = ./configure --target=$(TC) --host=$(TC) --enable-shared --disable-static --enable-rtadv ac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes
	build = make
endif
